### ISSUE TITLE
Enforce use of https

### ISSUE THREAD

**Issue by charphi** [amattioc/SDMX#102]
Currently, all built-in providers use http.
I think it might be a good idea to set https by default when that is possible.

Here is a list of providers that support https:

- ECB
- OECD
- OECD_RESTR
- ILO
- NBB

**Comment by amattioc** [comment]
Hi @charphi, that's a good point. Unfortunately there is a strange behaviour of the [ProxySelector ](https://github.com/amattioc/SDMX/blob/master/JAVA/src/it/bancaditalia/oss/sdmx/util/SdmxProxySelector.java) that someway breaks the automatic certificate checking (I suspect because the Proxy class does not completely support https). This would force https users that are behind proxies to have a locally configured keystore.

I'll try and find an alternative to the ProxySelector. Do you have any hints?

Best, Attilio

**Comment by charphi** [comment]
I don't think the ProxySelector is the problem because it doesn't deal with certificates.

In fact, some proxy servers rewrite SSL certificates for secure (HTTPS) remote hosts.
In these cases, you need to trust their proxy server certificate in order to prevent exceptions.
Some related info: https://support.sonatype.com/hc/en-us/articles/213464948-How-to-trust-the-SSL-certificate-issued-by-the-HTTP-proxy-server-in-Nexus 

You can also disable SSL check but it might pose a security threat (less important inside a corporate network).

**Comment by amattioc** [comment]
investigating...

**Comment by amattioc** [comment]
Hi @charphi 
I just added https support for ECB, OECD and NBB (5ed5749). 

I did not switch ILO because there is a problem with java 1.6:

`SEVERE: Exception. Class: javax.net.ssl.SSLHandshakeException .Message: Received fatal alert: handshake_failure`

The problems does not show up using java 1.7+, so I'll link the ILO https switch to the upgrade of the java support (#86).

Please let me know your thoughts.

Best, Attilio

**Comment by charphi** [comment]
It's ok for me.
Thanks.

**Comment by amattioc** [comment]
In case users need to switch back to **http** it is enough to add the following lines to the configuration file:

`providers.ECB.endpoint=https://sdw-wsrest.ecb.europa.eu/service`
`providers.OECD.endpoint=https://stats.oecd.org/restsdmx/sdmx.ashx`
`providers.NBB.endpoint=https://stat.nbb.be/RestSDMX/sdmx.ashx`
