### ISSUE TITLE
Code lables

### ISSUE THREAD

**Issue by dur41d** [amattioc/SDMX#123]
Is it currently possible to see the code labels in the Excel and STATA plugins?

For example, users would like to see the country names and not only the codes.

If not, is it on the road-map to support such feature?

Thanks

**Comment by amattioc** [comment]
Hi Duraid,

that could be an interesting task. Let me check if my understanding is correct. We're talking about data calls, right? And you mean replacing the ids that we actually set for metadata (e.g. dimensions and coded attributes) with the corresponding readable description (i.e. _'name'_ in the xml).

Am I correct?

Best, Attilio

**Comment by dur41d** [comment]
That's correct. It will be good to setup the software to be able to display: IDs, Names, or both (ex. AB:Albania).

**Comment by amattioc** [comment]
Yes, it definitely makes sense. Let me check how complex the change is, so to decide if it can be included in v1.7

**Comment by amattioc** [comment]
Hi @dur41d it'll be done in milestone version 1.8, I'll get back to you as soon as we have some details about the implementation.

**Comment by dur41d** [comment]
Sounds good. Thanks.

**Comment by amattioc** [comment]
Hi @dur41d sorry for getting back so late. 

In commit 29850baac44d81fbfe758777b3d3434504c17e87 I added the possibility to have the dimension and attribute code descriptions. In order to do it you'll have to set the `handle.sdmx.codes` parameter in the configuration file. 

As of today the possible values are:

- `code` : is the deafult behaviour and you'll get the code id 
- `description` : you'll get the code descritption
- `both` : you'll get something like **code_id(code_descritpion)**

Please note that this has an impact on the time series name: only if the option is set to **code** the name respects the sdmx convention for time series identifiers (e.g. **EXR.A.USD.EUR.SP00.A** and not **EXR.M(Monthly).USD(US dollar).EUR(Euro).SP00(Spot).A(Average)**)

I'll be glad to receive feedback from you and your users.

Best, Attilio

**Comment by dur41d** [comment]
Thanks @amattioc. I will download and test this version and let you know of any issues.

**Comment by dur41d** [comment]
Hi @amattioc. I downloaded and complied the commit 29850ba. I don't know if it's working properly. When running the SDMX.jar I always get  `both` even if i specify other options in the configuration file. 

In Excel I get `Error: Could not find or load main class it.bancaditalia.oss.sdmx.util.GetTimeSeries`.

**Comment by amattioc** [comment]
Hi @dur41d, the excel error is most probably due to the SDMX.jar not being found in the CLASSPATH. Please make sure that you correctly set the `SDMX_LIB` environment variable in you PC and that it points to the jar:

`SDMX_LIB=C:\full\path\to\SDMX.jar`

Regarding the options not being processed correctly, can you give me some details? Are you testing with the SDMX Helper?

Best, Attilio

**Comment by dur41d** [comment]
Hi @amattioc. You're right. I fixed the SDMX_LIB location and now it works.

I tested this query `UIS`, `DEM_ECO.DEC....AF` in excel and I found that there is no difference between `handle.sdmx.codes = both` and `desc` as they both display the code and the description.

Also, I found that the label in only displayed for dimensions and not attributes.

**Comment by amattioc** [comment]
Hi @dur41d the correct key value is `description`, not `desc`. If you set it this way it should work. In the next commit I'll add a further check in the configuration initialization for setting a warning on that.

Regarding the attribute descriptions that you do not see, I realized that there is still a missing part for the **observation level attributes** (and UIS seems to set only attributes at that level). 

![immagine](https://user-images.githubusercontent.com/8512242/27728379-16646f8e-5d82-11e7-86e2-323e20ed83c3.png)

Time series level attributes are already managed instead. 

![immagine](https://user-images.githubusercontent.com/8512242/27728437-4fd0a0ee-5d82-11e7-9acb-8962a2201e5a.png)

I'll add support for the observation level ones asap.

Let me know, Attilio

**Comment by dur41d** [comment]
Hi @amattioc. I changed it to `description` and it works as expected. 

Cheers.

**Comment by amattioc** [comment]
Great. I'll keep the issue open till I finish with the obs level attributes.

**Comment by amattioc** [comment]
Hi @dur41d, in commit e401cd23be9865aba3d52f76738767e56148b999 I added support for the obs level attributes. Now for the UIS query in excel I get this:

![immagine](https://user-images.githubusercontent.com/8512242/27739642-9985e53c-5daf-11e7-9623-711ba659dc6c.png)

Best, Attilio

**Comment by dur41d** [comment]
Hi @amattioc, I got the change all is working fine. Thanks for implementing the feature.

BTW, i found where i got the `desc` from. it's in the `configuration.properies` file. Please correct the typo so that other people don't have the same problem.

**Comment by amattioc** [comment]
Fixed, thanks
