### ISSUE TITLE
Trouble with Simple Eurostat Queries

### ISSUE THREAD

**Issue by larry77** [amattioc/SDMX#142]
Hello,
Very direct question: the following query works on my system without any problem

    df<- getTimeSeriesTable('EUROSTAT','hbs_exp_t121.A.*.BE|BG|CZ|DK|DE')

but this one

    df<- getTimeSeriesTable('EUROSTAT','hbs_exp_t121.A.*.*')

does not and I get warnings about the fact that I am making a large query, but the data set I am trying to download is actually rather small.
Here is my sessionInfo

     > sessionInfo()
     R version 3.4.1 (2017-06-30)
     Platform: x86_64-pc-linux-gnu (64-bit)
     Running under: Debian GNU/Linux 9 (stretch)

    Matrix products: default
    BLAS: /usr/lib/libblas/libblas.so.3.7.0
    LAPACK: /usr/lib/lapack/liblapack.so.3.7.0

    locale:
     [1] LC_CTYPE=en_GB.utf8          LC_NUMERIC=C                
     [3] LC_TIME=en_GB.utf8           LC_COLLATE=en_GB.utf8       
     [5] LC_MONETARY=en_GB.utf8       LC_MESSAGES=en_GB.utf8      
     [7] LC_PAPER=en_GB.utf8          LC_NAME=en_GB.utf8          
     [9] LC_ADDRESS=en_GB.utf8        LC_TELEPHONE=en_GB.utf8     
     [11] LC_MEASUREMENT=en_GB.utf8    LC_IDENTIFICATION=en_GB.utf8

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base 

Any idea of what the trouble is?

**Comment by amattioc** [comment]
Hi @larry77 today I tried the failing query and I get back a 51480 x 8 dataframe. The query should activate the 'late retrieval' mechanism, that is quite specific of the Eurostat provider.

You should receive this warning:

`INFO: The sdmx call returned messages in the footer:
 Message [code=413, severity=Infomation, url=http://ec.europa.eu/eurostat/SDMX/diss-web/file/, text=[Due to the large query the response will be written to a file which will be located under URL: http://ec.europa.eu/eurostat/SDMX/diss-web/file/, http://ec.europa.eu/eurostat/SDMX/diss-web/file/, Please check the location periodic every 5 minutes or at your preference.]]`

Immediately the connector should start polling the URL each 6 seconds waiting for the file to be reachable. The messages you should see are:

`set 20, 2017 1:52:46 PM it.bancaditalia.oss.sdmx.client.custom.EUROSTAT pollLateResponse INFO: Trying late retrieval with URL: http://ec.europa.eu/eurostat/SDMX/diss-web/file/. Attempt n: 1` <BR>
`set 20, 2017 1:52:52 PM it.bancaditalia.oss.sdmx.client.custom.EUROSTAT pollLateResponse
INFO: Trying late retrieval with URL: http://ec.europa.eu/eurostat/SDMX/diss-web/file/. Attempt n: 2` <BR>
`set 20, 2017 1:52:58 PM it.bancaditalia.oss.sdmx.client.custom.EUROSTAT pollLateResponse
INFO: Trying late retrieval with URL: http://ec.europa.eu/eurostat/SDMX/diss-web/file/. Attempt n: 3` <BR>

By default the connector will try 10 times before giving up. The numer of retries is configurable.

Do you see this behaviour or do you get a different error?

Best, Attilio

**Comment by larry77** [comment]
Hi Attilio,
It appears the problem may be on EUROSTAT side, meaning that sometimes 10 attempts are not enough to retrieve the data set.
Can you tell me how to create a query which tries e.g. 20 times before giving up? After that, we can mark this as close.
Thanks!

**Comment by amattioc** [comment]
Hi @larry77 , you can use the property **late.response.retries**. It has to be set in the [configuration file](https://github.com/amattioc/SDMX/wiki/System-Configuration#configuration-file-location)

E.g:

`late.response.retries = 20`

Please let me know if this solves your issue.

Best, Attilio
