### ISSUE TITLE
IOTS - highly structured statistical products

### ISSUE THREAD

**Issue by antaldaniel** [amattioc/SDMX#146]
Apologies if this is not a concern to you, maybe I am doing something wrong.  I am writing an R package that will handle [input-output tables,](https://github.com/antaldaniel/iotables) which are probably the most complex statistical products, since they give a complete overview of the national accounts.    I am already more or less finished with Eurostat, and want to use your package as a dependency to OECD. 

I need to retrieve this table, maybe with a different time span, or year by year. 

`http://stats.oecd.org/restsdmx/sdmx.ashx/GetData/IOTS/TTL.AUS.TTL_C01T05+TTL_C10T14+TTL_C15T16+TTL_C17T19+TTL_C20+TTL_C21T22+TTL_C23+TTL_C24+TTL_C25+TTL_C26+TTL_C27+TTL_C28+TTL_C29+TTL_C30T33X+TTL_C31+TTL_C34+TTL_C35+TTL_C36T37+TTL_C40T41+TTL_C45+TTL_C50T52+TTL_C55+TTL_C60T63+TTL_C64+TTL_C65T67+TTL_C70+TTL_C71+TTL_C72+TTL_C73T74+TTL_C75+TTL_C80+TTL_C85+TTL_C90T93+TTL_C95+DOM_C01T05+DOM_C10T14+DOM_C15T16+DOM_C17T19+DOM_C20+DOM_C21T22+DOM_C23+DOM_C24+DOM_C25+DOM_C26+DOM_C27+DOM_C28+DOM_C29+DOM_C30T33X+DOM_C31+DOM_C34+DOM_C35+DOM_C36T37+DOM_C40T41+DOM_C45+DOM_C50T52+DOM_C55+DOM_C60T63+DOM_C64+DOM_C65T67+DOM_C70+DOM_C71+DOM_C72+DOM_C73T74+DOM_C75+DOM_C80+DOM_C85+DOM_C90T93+DOM_C95+IMP_C01T05+IMP_C10T14+IMP_C15T16+IMP_C17T19+IMP_C20+IMP_C21T22+IMP_C23+IMP_C24+IMP_C25+IMP_C26+IMP_C27+IMP_C28+IMP_C29+IMP_C30T33X+IMP_C31+IMP_C34+IMP_C35+IMP_C36T37+IMP_C40T41+IMP_C45+IMP_C50T52+IMP_C55+IMP_C60T63+IMP_C64+IMP_C65T67+IMP_C70+IMP_C71+IMP_C72+IMP_C73T74+IMP_C75+IMP_C80+IMP_C85+IMP_C90T93+IMP_C95+TXS_INT_FNL+TTL_INT_FNL+VALU+LABR+OTXS+GOPS+CFC+NOPS+OUTPUT+TOTAL+CTOTAL+DISC.C01T05+C10T14+C15T16+C17T19+C20+C21T22+C23+C24+C25+C26+C27+C28+C29+C30T33X+C31+C34+C35+C36T37+C40T41+C45+C50T52+C55+C60T63+C64+C65T67+C70+C71+C72+C73T74+C75+C80+C85+C90T93+C95+HFCE+NPISH+GGFC+GFCF+INVNT+CONS_ABR+CONS_NONRES+EXPO+IMPO+ICESHR/all?startTime=1995&endTime=2011`

This is the long-form version of a table, and it is not really a time-series.  I am getting 

> java.lang.NoSuchMethodException: No suitable method for the given parameters

errors, regardless if I use 
`result = getTimeSeries('OECD', my_url_short, start = 2008, end = 2011)
`or 
`result2 <- getSDMX('OECD', my_url_short, start = 2008, end = 2011)`

The my_url short is the string above, ie. 
`IOTS/TTL.AUS.TTL_C01T05+[...]++EXPO+IMPO+ICESHR`
without the time part. 

Is there a way to simplyfy the query, using some wild card.  Or shall I retrieve them line by line, i.e. as 60 individual lists?  More generally, is there any guidance to retrieve more structured data products than a time series or a panel?

**Comment by amattioc** [comment]
Hi @antaldaniel 

if you need a **time series** list you can use:

`
tslist = getTimeSeries(provider = 'OECD', id = 'IOTS/TTL.AUS.TTL_C01T05+TTL_C10T14+TTL_C15T16+TTL_C17T19+TTL_C20+TTL_C21T22+TTL_C23+TTL_C24+TTL_C25+TTL_C26+TTL_C27+TTL_C28+TTL_C29+TTL_C30T33X+TTL_C31+TTL_C34+TTL_C35+TTL_C36T37+TTL_C40T41+TTL_C45+TTL_C50T52+TTL_C55+TTL_C60T63+TTL_C64+TTL_C65T67+TTL_C70+TTL_C71+TTL_C72+TTL_C73T74+TTL_C75+TTL_C80+TTL_C85+TTL_C90T93+TTL_C95+DOM_C01T05+DOM_C10T14+DOM_C15T16+DOM_C17T19+DOM_C20+DOM_C21T22+DOM_C23+DOM_C24+DOM_C25+DOM_C26+DOM_C27+DOM_C28+DOM_C29+DOM_C30T33X+DOM_C31+DOM_C34+DOM_C35+DOM_C36T37+DOM_C40T41+DOM_C45+DOM_C50T52+DOM_C55+DOM_C60T63+DOM_C64+DOM_C65T67+DOM_C70+DOM_C71+DOM_C72+DOM_C73T74+DOM_C75+DOM_C80+DOM_C85+DOM_C90T93+DOM_C95+IMP_C01T05+IMP_C10T14+IMP_C15T16+IMP_C17T19+IMP_C20+IMP_C21T22+IMP_C23+IMP_C24+IMP_C25+IMP_C26+IMP_C27+IMP_C28+IMP_C29+IMP_C30T33X+IMP_C31+IMP_C34+IMP_C35+IMP_C36T37+IMP_C40T41+IMP_C45+IMP_C50T52+IMP_C55+IMP_C60T63+IMP_C64+IMP_C65T67+IMP_C70+IMP_C71+IMP_C72+IMP_C73T74+IMP_C75+IMP_C80+IMP_C85+IMP_C90T93+IMP_C95+TXS_INT_FNL+TTL_INT_FNL+VALU+LABR+OTXS+GOPS+CFC+NOPS+OUTPUT+TOTAL+CTOTAL+DISC.C01T05+C10T14+C15T16+C17T19+C20+C21T22+C23+C24+C25+C26+C27+C28+C29+C30T33X+C31+C34+C35+C36T37+C40T41+C45+C50T52+C55+C60T63+C64+C65T67+C70+C71+C72+C73T74+C75+C80+C85+C90T93+C95+HFCE+NPISH+GGFC+GFCF+INVNT+CONS_ABR+CONS_NONRES+EXPO+IMPO+ICESHR', start = '1995', end='2011')
`

but since no frequencies are set, you could prefer a data.frame: 

`table = getTimeSeriesTable(provider = 'OECD', id = 'IOTS/TTL.AUS.TTL_C01T05+TTL_C10T14+TTL_C15T16+TTL_C17T19+TTL_C20+TTL_C21T22+TTL_C23+TTL_C24+TTL_C25+TTL_C26+TTL_C27+TTL_C28+TTL_C29+TTL_C30T33X+TTL_C31+TTL_C34+TTL_C35+TTL_C36T37+TTL_C40T41+TTL_C45+TTL_C50T52+TTL_C55+TTL_C60T63+TTL_C64+TTL_C65T67+TTL_C70+TTL_C71+TTL_C72+TTL_C73T74+TTL_C75+TTL_C80+TTL_C85+TTL_C90T93+TTL_C95+DOM_C01T05+DOM_C10T14+DOM_C15T16+DOM_C17T19+DOM_C20+DOM_C21T22+DOM_C23+DOM_C24+DOM_C25+DOM_C26+DOM_C27+DOM_C28+DOM_C29+DOM_C30T33X+DOM_C31+DOM_C34+DOM_C35+DOM_C36T37+DOM_C40T41+DOM_C45+DOM_C50T52+DOM_C55+DOM_C60T63+DOM_C64+DOM_C65T67+DOM_C70+DOM_C71+DOM_C72+DOM_C73T74+DOM_C75+DOM_C80+DOM_C85+DOM_C90T93+DOM_C95+IMP_C01T05+IMP_C10T14+IMP_C15T16+IMP_C17T19+IMP_C20+IMP_C21T22+IMP_C23+IMP_C24+IMP_C25+IMP_C26+IMP_C27+IMP_C28+IMP_C29+IMP_C30T33X+IMP_C31+IMP_C34+IMP_C35+IMP_C36T37+IMP_C40T41+IMP_C45+IMP_C50T52+IMP_C55+IMP_C60T63+IMP_C64+IMP_C65T67+IMP_C70+IMP_C71+IMP_C72+IMP_C73T74+IMP_C75+IMP_C80+IMP_C85+IMP_C90T93+IMP_C95+TXS_INT_FNL+TTL_INT_FNL+VALU+LABR+OTXS+GOPS+CFC+NOPS+OUTPUT+TOTAL+CTOTAL+DISC.C01T05+C10T14+C15T16+C17T19+C20+C21T22+C23+C24+C25+C26+C27+C28+C29+C30T33X+C31+C34+C35+C36T37+C40T41+C45+C50T52+C55+C60T63+C64+C65T67+C70+C71+C72+C73T74+C75+C80+C85+C90T93+C95+HFCE+NPISH+GGFC+GFCF+INVNT+CONS_ABR+CONS_NONRES+EXPO+IMPO+ICESHR', start = '1995', end='2011')
`

Furthermore, if you are looking for a **shorter query**, you could wildcard the last two dimensions:

`
table_all = getTimeSeriesTable(provider = 'OECD', id = 'IOTS/TTL.AUS..', start = '1995', end='2011')
`

You'll get a 30k rows table and you may subset afterwards.

I suggest you could use the helper for building effective queries; just type:

`sdmxHelp()`

Does this help?

Best, Attilio

**Comment by antaldaniel** [comment]
Absolutely, thank you very much your kind and quick response!

I tried to work with the `sdmxHelp()` but this query got too long, and when I tried to make it short, I mistakenly put only one . to the id end. 

I will create a wrapper around this in my package that will download and re-format the tables for further use. 

Thank you very much!

**Comment by amattioc** [comment]
You are welcome!
