### ISSUE TITLE
Large Queries with Eurostat and Filtering on Time

### ISSUE THREAD

**Issue by larry77** [amattioc/SDMX#180]
Dear All,
I need to retrieve quite a lot of data from the bop_c6_q dataset in Eurostat.
It has a similar structure to the bop_eu6_q and it contains quarterly data.
The following query runs without issues

     dfEU  <-  getTimeSeriesTable('EUROSTAT',    'bop_eu6_q/Q.MIO_EUR.FA__D__F.S1.S1.NSA.LIAB+NET+ASS.UK+EU27_2019+IN+EUI+CN_X_HK+EXT_EA19+BR+EXT_EU28+OFFSHO+CH+EU28+HK+EXT_EU27_2019+JP+RU+US+CA.EU28')

    df2 <-  getTimeSeriesTable('EUROSTAT', 'bop_c6_q/Q.MIO_EUR.FA__D__F.S1.S1.ASS+NET+LIAB.DE+BE+FI+RU+HK+PT+BG+EXT_EA19+JP+DK+LT+LU+HR+LV+FR+HU+BR+SE+WRL_REST+EU28+SI+UK+SK+EUI+IE+CA+US+EE+CN_X_HK+OFFSHO+EA19+CH+IN+EL+MT+EU27_2019+IT+ES+AT+EXT_EU28+EXT_EU27_2019+CY+CZ+PL+RO+NL.DE+NO+RS+BE+FI+PT+BG+DK+LT+LU+HR+LV+FR+HU+SE+SI+UK+SK+ME+IE+MK+EE+CH+EL+MT+IS+IT+AL+ES+AT+XK+CY+CZ+PL+RO+NL+TR+BA')

fails badly.
What I need are: all the reporters and partners for the filters that I apply and the time after 1999 (can I filter the time?).
Also, can I use a wildcard instead of listing all the partners and the reporters?
Any suggestion is appreciated.

**Comment by amattioc** [comment]
Hi @larry77 

you can filter on time by passing the **start** and **end** arguments to the call. You can also wildcard dimensions leaving them **blank** (in this case you'll probably receive more data than needed and you'll have to filter the dataframe right after downloading it).

When too much data is requested, the eurostat provider will automatically activate an asynchronous mechanism, that prepares a zip file on a specific URL. The connector is able to manage this, but sometimes the time needed to terminate the interaction is too long and it closes the connection. 

To avoid this you could slice your request on time (as you were supposing):

`res=NULL`
`for(x in 1999:2019){`
`res=rbind(res, getTimeSeriesTable('EUROSTAT', 'bop_c6_q/Q.MIO_EUR.FA__D__F.S1.S1.ASS+NET+LIAB..', start = as.character(x), end = as.character(x+1)))`
`}`

> str(res)
'data.frame':	849528 obs. of  14 variables:
 $ TIME_PERIOD        : chr  "1999-Q1" "1999-Q2" "1999-Q3" "1999-Q4" ...
 $ OBS_VALUE          : num  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN ...
 $ ID                 : chr  "bop_c6_q.Q.MIO_EUR.FA__D__F.S1.S1.ASS.AT.AL" "bop_c6_q.Q.MIO_EUR.FA__D__F.S1.S1.ASS.AT.AL" "bop_c6_q.Q.MIO_EUR.FA__D__F.S1.S1.ASS.AT.AL" "bop_c6_q.Q.MIO_EUR.FA__D__F.S1.S1.ASS.AT.AL" ...
 $ OBS_STATUS         : chr  "na" "na" "na" "na" ...
 $ FREQ               : chr  "Q" "Q" "Q" "Q" ...
 $ CURRENCY           : chr  "MIO_EUR" "MIO_EUR" "MIO_EUR" "MIO_EUR" ...
 $ BOP_ITEM           : chr  "FA__D__F" "FA__D__F" "FA__D__F" "FA__D__F" ...
 $ SECTOR10           : chr  "S1" "S1" "S1" "S1" ...
 $ SECTPART           : chr  "S1" "S1" "S1" "S1" ...
 $ STK_FLOW           : chr  "ASS" "ASS" "ASS" "ASS" ...
 $ PARTNER            : chr  "AT" "AT" "AT" "AT" ...
 $ GEO                : chr  "AL" "AL" "AL" "AL" ...
 $ CONNECTORS_AUTONAME: chr  "ESTAT,bop_c6_q,1.0 ; Balance of payments by country - quarterly data (BPM6), Q(Quarterly), MIO_EUR(Million euro"| __truncated__ "ESTAT,bop_c6_q,1.0 ; Balance of payments by country - quarterly data (BPM6), Q(Quarterly), MIO_EUR(Million euro"| __truncated__ "ESTAT,bop_c6_q,1.0 ; Balance of payments by country - quarterly data (BPM6), Q(Quarterly), MIO_EUR(Million euro"| __truncated__ "ESTAT,bop_c6_q,1.0 ; Balance of payments by country - quarterly data (BPM6), Q(Quarterly), MIO_EUR(Million euro"| __truncated__ ...
 $ OBS_FLAG           : chr  NA NA NA NA ...
  attr(*, "IS_ERROR")= logi FALSE
  attr(*, "IS_NUMERIC")= logi TRUE

**Comment by larry77** [comment]
Thanks a lot! I like the idea of iterating on the years and I will be applying this "trick" to a number of other cases in the future.

**Comment by larry77** [comment]
Maybe I will close this soon again, but right know this solution does not work any longer. Most likely it is an issue, just for a change, on the estat site, but can you please have a look?
Reprex enclosed and thanks!

``` r

library(RJSDMX)
#> Loading required package: rJava
#> Loading required package: zoo
#> 
#> Attaching package: 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric

ini_year <- 2018
end_year <- 2019

##In case I need to break my query

bop_c6 <- NULL
for(x in ini_year:end_year){
    print("processing year")
    print(x)
bop_c6 <- rbind(bop_c6, getTimeSeriesTable('EUROSTAT', 'bop_c6_q/Q.MIO_EUR.FA__D__F.S1.S1.ASS+NET+LIAB..', start = as.character(x), end = as.character(x+1)))
}
#> [1] "processing year"
#> [1] 2018
#> Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl, : it.bancaditalia.oss.sdmx.exceptions.SdmxXmlContentException: Late retrieval failed.
```

<sup>Created on 2020-10-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by amattioc** [comment]
Hi @larry77 today it works for me, but I think that the behaviour you describe may depend on the time that the provider takes to prepare the dataset when the request exceeds the limits for synchronous response (this is a eurostat specific mechanism). 

What you see is probably a number (10 is the default) of attempts on a URL and a log like this:

`nov 02, 2020 11:16:38 AM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
INFORMAZIONI: Contacting web service with query: http://ec.europa.eu/eurostat/SDMX/diss-web/file/oB4MOgeREOHyNio5`

and if the result is not got after 10 attempts (one every 6 secs) you get a failure:

`nov 02, 2020 11:16:44 AM it.bancaditalia.oss.sdmx.client.custom.EUROSTAT getTimeSeries
INFORMAZIONI: Late retrieval attempt 10 failed with exception SdmxResponseException: (100): No results matching the query.`

If this is the case, you can do two things:

1. try to avoid the asynchronous mechanism by reducing the result size (e.g. retrieve single quarters or iterate on groups of codes instead of using a full wildcard)

2. configure the connector to poll for a longer time by means of the  [late.response.retries](https://github.com/amattioc/SDMX/wiki/System-Configuration#eurostat-delayed-response) configuration parameter.

Please let me know if this helps.

**Comment by larry77** [comment]
Thanks. I will mark this close. In general, it seems to me that there is a degradation of the service offered by EUROSTAT.
