### ISSUE TITLE
ABS wildcard white space  error 

### ISSUE THREAD

**Issue by pdgilbert** [amattioc/SDMX#19]
works:
 tts <-  getSDMX('ABS', 'CPI.1.50.10001.10.Q') 
 names(tts)
[1] "CPI.1.50.10001.10.Q"

fails:
 tts <-  getSDMX('ABS', 'CPI.1.*.10001.10.Q') 
Dec 12, 2014 2:10:41 PM it.bankitalia.reri.sia.sdmx.client.custom.RestSdmx20Client getTimeSeries
SEVERE: Exception caught parsing results from call to provider ABS
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  it.bankitalia.reri.sia.util.SdmxException: Exception. Class: javax.xml.stream.XMLStreamException .Message: ParseError at [row,col]:[1,63]
Message: White spaces are required between publicId and systemId.

**Comment by byrnli** [comment]
More of a workaround than a solution but the 'OR' operator can be used to wildcard dimensions that would otherwise fail on the ABS service. So the following would get all members from the second and third dimensions 

http://stat.abs.gov.au/restsdmx/sdmx.ashx/GetData/ABS_NRP9_ASGS/EC41.+.+.A/ABS?format=compact_v2

**Comment by amattioc** [comment]
Thanks @byrnli, that's a good workaround and it works without changes in the connectors:

`tts = getSDMX('ABS', 'ABS_NRP9_ASGS/EC41.+.+.A')`

I close the issue. I'll add an update as the definitive fix is available on the provider.
