### ISSUE TITLE
Support for SDMX-JSON

### ISSUE THREAD

**Issue by larry77** [amattioc/SDMX#193]
Dear All,
More than an issue, it is a request for an enhancement.
Some providers are shifting towards SDMX-JSON data structures.
As far as I looked, there is no support for this in RJSDMX. If it is so, are you considering to add this in the near future?
Looking forward to your reply.

**Comment by amattioc** [comment]
Hi @larry77 , so far we have not yet needed to add json support because all providers that use it are also providing XML messages, Did you find any JSON only providers?

Thanks, Attilio

**Comment by larry77** [comment]
No, or not yet :-).
In any case, I believe it is an option worth exploring. A large dataset is definitely more compact as a JSON than as an XML, so whenever possible there are some advantages in processing a JSON.

**Comment by amattioc** [comment]
Hi, you're right, it's an interesting option for the future. For now we're waiting for the new SDMX 3.0 version to be published, because there will be a lot of work to do to update the software. That could be the right time to add json support probably.

Thanks again for the suggestion, I'll leave the issue open as a reminder. Attilio

**Comment by amattioc** [comment]
Closing as json is not planned for the near future.
