### ISSUE TITLE
 query with + or |

### ISSUE THREAD

**Issue by pdgilbert** [amattioc/SDMX#22]
It would be nice  if a query with + or | would return results in the order of the query specification. (Enhancement request)

**Comment by amattioc** [comment]
This can now be achieved querying a list of single identifiers (separated by a ';'). 

This way the order is respected. E.g. 

`> l=getTimeSeries('ECB', 'EXR.A.USD.EUR.SP00.A;EXR.M.USD.EUR.SP00.A;EXR.A.GBP.EUR.SP00.A;EXR.M.GBP.EUR.SP00.A')`
`> names(l)`
`[1] "EXR.A.USD.EUR.SP00.A" "EXR.M.USD.EUR.SP00.A" "EXR.A.GBP.EUR.SP00.A" "EXR.M.GBP.EUR.SP00.A"`

while

`> l=getTimeSeries('ECB', 'EXR.A+M.USD+GBP.EUR.SP00.A')`
`> names(l)`
`[1] "EXR.A.GBP.EUR.SP00.A" "EXR.A.USD.EUR.SP00.A" "EXR.M.GBP.EUR.SP00.A" "EXR.M.USD.EUR.SP00.A"`

It is not very efficient, because it calls the web service once per identifier, but it should provide the needed behaviour...

Best, Attilio
