### ISSUE TITLE
Error downloading from IMF (br vs </br>)

### ISSUE THREAD

**Issue by giannilmbd** [amattioc/SDMX#234]
Hi,
Thanks for putting this package together.
I'm trying to download some IMF data (lots' of BoP data).
Whether I try with the java application or within R I get the following error message 

```Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  it.bancaditalia.oss.sdmx.exceptions.SdmxXmlParsingException: Error detected while parsing SDMX response: ParseError at [row,col]:[1,177]
Message:` The element type "br" must be terminated by the matching end-tag "</br>".
```
The command I run is (generated by the Helper Tool)

result <- getTimeSeries('IMF2', 'DS-BOP_2023M05/Q.SE+PY+CZ+MU+TJ+IN+DZ+VU+AR+KI+AN+All_Countries+BG+LK+LS+ZA+MD+TN+PK+HK+KW+IQ+NO+CD+MZ+EC+SB+TR+AU+AZ+NI+CG+GA+UZ+MX+NE+LT+HR+MO+MH+BS+U2+MT+BH+BZ+AD+DM+SC+AW+NZ+KY+JM+MA+RU+BI+AG+LA+SG+TG+LV+MV+TZ+HU+BT+MN+1C_355+NC+AM+CN+GW+BR+PE+IE+SI+CO+IIP_Reporters+1C_473+SZ+1C_459+NP+RO+JP+GE+NG+AF+CM+CV+CCR+TV+ER+CY+CSH+FI+TC+DJ+LR+VN+FO+SY+AI+LC+LB+CH+PT+FR+ET+SO+ZM+JO+PH+TL+LU+CR+MM+MY+ST+AO+GM+YE+KE+BF+IR+TD+TH+MK+BN+R1+TM+SM+BJ+SPE_REPORTERS+OM+KM+SD+CF+IL+KH+VC+PS+KN+VE+TW+KZ+EG+ME+UG+NL+CA+BM+DO+CL+BE+5Y+NR+PW+DK+FM+BO+KG+SK+AL+NA+FJ+ML+YUC+IT+SL+PF+RS+SA+AT+RW+GN+BW+IS+PL+SR+GQ+UA+BD+GB+WS+MS+BB+TT+BOP_Reporters+DE+HN+LY+UY+ES+SS+ZW+XK+QA+GH+HT+MG+SX+GD+MR+CW+US+EE+BA+ID+TO+PA+GY+SN+CI+GT+PG+SV+BY+GR+KR+MW.BEFPDORPP_BP6_USD+BEFPDONFSAI_BP6_USD+BEFPDOFCAP_BP6_USD+BEFPDDCAA_BP6_USD+BEFPDONFAAPI_BP6_USD+BEFPDGRAI_BP6_USD+BEFPDCBRA_BP6_USD+BEFPDORAP_BP6_USD+BEFPDGCAP_BP6_USD+BEFPDDCRAP_BP6_USD+BEFPEO_BP6_USD+BEFPDOSAI_BP6_USD+BEFPDCB_BP6_USD+BEFPDDCRAI_BP6_USD+BEFPDONFRAI_BP6_USD+BEFPDONFSA_BP6_USD+BEFPDDCAAI_BP6_USD+BEFPDGPB_BP6_USD+BEFPDGCAI_BP6_USD+BEFPDCBSA_BP6_USD+BEFPDONFAAP_BP6_USD+BEFPDONFRPP_BP6_USD+BEFPDCBCAI_BP6_USD+BEFPEG_BP6_USD+BEFPDCBNS_BP6_USD+BEFPDOAAPI_BP6_USD+BEFPDCBAAP_BP6_USD+BEFPE_BP6_USD+BEFPD_BP6_USD+BEFPDORP_BP6_USD+BEFPDG_BP6_USD+BEFPDORAI_BP6_USD+BEFPDCBAAPI_BP6_USD+BEFPDOFPB_BP6_USD+BEFPDGAAI_BP6_USD+BEFPDDCRPI_BP6_USD+BEFPDGRPI_BP6_USD+BEFPDDCRP_BP6_USD+BEFPDOAAP_BP6_USD+BEFPDGSAI_BP6_USD+BEFPDONFRPI_BP6_USD+BEFPEDC_BP6_USD+BEFPDOFAAP_BP6_USD+BEFPDONFAAI_BP6_USD+BEFPDDCRA_BP6_USD+BEFPEONF_BP6_USD+BEFPDCBCAP_BP6_USD+BEFPDONFAA_BP6_USD+BEFPDONFRAP_BP6_USD+BEFPDDCSAP_BP6_USD+BEFPDCBSAI_BP6_USD+BEFPDDCAAPI_BP6_USD+BEFPECB_BP6_USD+BEFPEOF_BP6_USD+BEFPDOCAI_BP6_USD+BEFPDOFSAI_BP6_USD+BEFPDGRPP_BP6_USD+BEFPDOAAI_BP6_USD+BEFPDCBRPP_BP6_USD+BEFPDGNS_BP6_USD+BEFPDOFRAP_BP6_USD+BEFPDGSAP_BP6_USD+BEFPDOF_BP6_USD+BEFPDOAA_BP6_USD+BEFPDONFCAP_BP6_USD+BEFPDOFRA_BP6_USD+BEFPDGCA_BP6_USD+BEFPDOFRP_BP6_USD+BEFPDOFRPP_BP6_USD+BEFPDONFRP_BP6_USD+BEFPDDCPB_BP6_USD+BEFPDCBRAI_BP6_USD+BEFPDCBRAP_BP6_USD+BEFPDDCSAI_BP6_USD+BEFPDDCAAP_BP6_USD+BEFPDONFPB_BP6_USD+BEFPDOFSA_BP6_USD+BEFPDDC_BP6_USD+BEFPDDCNC_BP6_USD+BEFPDGRA_BP6_USD+BEFPDONF_BP6_USD+BEFPDGRAP_BP6_USD+BEFPDCBAA_BP6_USD+BEFPDDCSA_BP6_USD+BEFPDONS_BP6_USD+BEFPDGRP_BP6_USD+BEFPDOFAAPI_BP6_USD+BEFPDCBRP_BP6_USD+BEFPDOFAA_BP6_USD+BEFPDCBCA_BP6_USD+BEFPDOFCA_BP6_USD+BEFPDDCCAP_BP6_USD+BEFPDDCRPP_BP6_USD+BEFPDOSA_BP6_USD+BEFPDOFCAI_BP6_USD+BEFPDOFRAI_BP6_USD+BEFPDCBSAP_BP6_USD+BEFPDORA_BP6_USD+BEFPDONFSAP_BP6_USD+BEFPDONFNS_BP6_USD+BEFPDORPI_BP6_USD+BEFPDOCA_BP6_USD+BEFPDOFSAP_BP6_USD+BEFPDOFRPI_BP6_USD+BEFPDDCCAI_BP6_USD+BEFPDOFNS_BP6_USD+BEFPDDCCA_BP6_USD+BEFPDONFRA_BP6_USD+BEFPDO_BP6_USD+BEFPDONFCA_BP6_USD+BEFPDOSAP_BP6_USD+BEFPDCBAAI_BP6_USD+BEFPDOPB_BP6_USD+BEFPDGAAPA_BP6_USD+BEFPDCBPB_BP6_USD+BEFPDGAAP_BP6_USD+BEFPDCBRPI_BP6_USD+BEFPDGAA_BP6_USD+BEFPDOCAP_BP6_USD+BEFPDOFAAI_BP6_USD+BEFPDONFCAI_BP6_USD+BEFPDGSA_BP6_USD+BEFP_BP6_USD');

**Comment by vpinna80** [comment]
Hi @giannilmbd ,
It isn't a problem of the connector but of the IMF provider. 
If you put the generated url into a browser, you'll see that the response tells you that the url was rejected.
I think that is because it is too long; try to split your list of codes into multiple queries.

You can check for yourself by clicking on the [generated url in the log](http://dataservices.imf.org/REST/SDMX_XML.svc/CompactData/BOP_2023M05/Q.SE%2BPY%2BCZ%2BMU%2BTJ%2BIN%2BDZ%2BVU%2BAR%2BKI%2BAN%2BAll_Countries%2BBG%2BLK%2BLS%2BZA%2BMD%2BTN%2BPK%2BHK%2BKW%2BIQ%2BNO%2BCD%2BMZ%2BEC%2BSB%2BTR%2BAU%2BAZ%2BNI%2BCG%2BGA%2BUZ%2BMX%2BNE%2BLT%2BHR%2BMO%2BMH%2BBS%2BU2%2BMT%2BBH%2BBZ%2BAD%2BDM%2BSC%2BAW%2BNZ%2BKY%2BJM%2BMA%2BRU%2BBI%2BAG%2BLA%2BSG%2BTG%2BLV%2BMV%2BTZ%2BHU%2BBT%2BMN%2B1C_355%2BNC%2BAM%2BCN%2BGW%2BBR%2BPE%2BIE%2BSI%2BCO%2BIIP_Reporters%2B1C_473%2BSZ%2B1C_459%2BNP%2BRO%2BJP%2BGE%2BNG%2BAF%2BCM%2BCV%2BCCR%2BTV%2BER%2BCY%2BCSH%2BFI%2BTC%2BDJ%2BLR%2BVN%2BFO%2BSY%2BAI%2BLC%2BLB%2BCH%2BPT%2BFR%2BET%2BSO%2BZM%2BJO%2BPH%2BTL%2BLU%2BCR%2BMM%2BMY%2BST%2BAO%2BGM%2BYE%2BKE%2BBF%2BIR%2BTD%2BTH%2BMK%2BBN%2BR1%2BTM%2BSM%2BBJ%2BSPE_REPORTERS%2BOM%2BKM%2BSD%2BCF%2BIL%2BKH%2BVC%2BPS%2BKN%2BVE%2BTW%2BKZ%2BEG%2BME%2BUG%2BNL%2BCA%2BBM%2BDO%2BCL%2BBE%2B5Y%2BNR%2BPW%2BDK%2BFM%2BBO%2BKG%2BSK%2BAL%2BNA%2BFJ%2BML%2BYUC%2BIT%2BSL%2BPF%2BRS%2BSA%2BAT%2BRW%2BGN%2BBW%2BIS%2BPL%2BSR%2BGQ%2BUA%2BBD%2BGB%2BWS%2BMS%2BBB%2BTT%2BBOP_Reporters%2BDE%2BHN%2BLY%2BUY%2BES%2BSS%2BZW%2BXK%2BQA%2BGH%2BHT%2BMG%2BSX%2BGD%2BMR%2BCW%2BUS%2BEE%2BBA%2BID%2BTO%2BPA%2BGY%2BSN%2BCI%2BGT%2BPG%2BSV%2BBY%2BGR%2BKR%2BMW.BEFPDORPP_BP6_USD%2BBEFPDONFSAI_BP6_USD%2BBEFPDOFCAP_BP6_USD%2BBEFPDDCAA_BP6_USD%2BBEFPDONFAAPI_BP6_USD%2BBEFPDGRAI_BP6_USD%2BBEFPDCBRA_BP6_USD%2BBEFPDORAP_BP6_USD%2BBEFPDGCAP_BP6_USD%2BBEFPDDCRAP_BP6_USD%2BBEFPEO_BP6_USD%2BBEFPDOSAI_BP6_USD%2BBEFPDCB_BP6_USD%2BBEFPDDCRAI_BP6_USD%2BBEFPDONFRAI_BP6_USD%2BBEFPDONFSA_BP6_USD%2BBEFPDDCAAI_BP6_USD%2BBEFPDGPB_BP6_USD%2BBEFPDGCAI_BP6_USD%2BBEFPDCBSA_BP6_USD%2BBEFPDONFAAP_BP6_USD%2BBEFPDONFRPP_BP6_USD%2BBEFPDCBCAI_BP6_USD%2BBEFPEG_BP6_USD%2BBEFPDCBNS_BP6_USD%2BBEFPDOAAPI_BP6_USD%2BBEFPDCBAAP_BP6_USD%2BBEFPE_BP6_USD%2BBEFPD_BP6_USD%2BBEFPDORP_BP6_USD%2BBEFPDG_BP6_USD%2BBEFPDORAI_BP6_USD%2BBEFPDCBAAPI_BP6_USD%2BBEFPDOFPB_BP6_USD%2BBEFPDGAAI_BP6_USD%2BBEFPDDCRPI_BP6_USD%2BBEFPDGRPI_BP6_USD%2BBEFPDDCRP_BP6_USD%2BBEFPDOAAP_BP6_USD%2BBEFPDGSAI_BP6_USD%2BBEFPDONFRPI_BP6_USD%2BBEFPEDC_BP6_USD%2BBEFPDOFAAP_BP6_USD%2BBEFPDONFAAI_BP6_USD%2BBEFPDDCRA_BP6_USD%2BBEFPEONF_BP6_USD%2BBEFPDCBCAP_BP6_USD%2BBEFPDONFAA_BP6_USD%2BBEFPDONFRAP_BP6_USD%2BBEFPDDCSAP_BP6_USD%2BBEFPDCBSAI_BP6_USD%2BBEFPDDCAAPI_BP6_USD%2BBEFPECB_BP6_USD%2BBEFPEOF_BP6_USD%2BBEFPDOCAI_BP6_USD%2BBEFPDOFSAI_BP6_USD%2BBEFPDGRPP_BP6_USD%2BBEFPDOAAI_BP6_USD%2BBEFPDCBRPP_BP6_USD%2BBEFPDGNS_BP6_USD%2BBEFPDOFRAP_BP6_USD%2BBEFPDGSAP_BP6_USD%2BBEFPDOF_BP6_USD%2BBEFPDOAA_BP6_USD%2BBEFPDONFCAP_BP6_USD%2BBEFPDOFRA_BP6_USD%2BBEFPDGCA_BP6_USD%2BBEFPDOFRP_BP6_USD%2BBEFPDOFRPP_BP6_USD%2BBEFPDONFRP_BP6_USD%2BBEFPDDCPB_BP6_USD%2BBEFPDCBRAI_BP6_USD%2BBEFPDCBRAP_BP6_USD%2BBEFPDDCSAI_BP6_USD%2BBEFPDDCAAP_BP6_USD%2BBEFPDONFPB_BP6_USD%2BBEFPDOFSA_BP6_USD%2BBEFPDDC_BP6_USD%2BBEFPDDCNC_BP6_USD%2BBEFPDGRA_BP6_USD%2BBEFPDONF_BP6_USD%2BBEFPDGRAP_BP6_USD%2BBEFPDCBAA_BP6_USD%2BBEFPDDCSA_BP6_USD%2BBEFPDONS_BP6_USD%2BBEFPDGRP_BP6_USD%2BBEFPDOFAAPI_BP6_USD%2BBEFPDCBRP_BP6_USD%2BBEFPDOFAA_BP6_USD%2BBEFPDCBCA_BP6_USD%2BBEFPDOFCA_BP6_USD%2BBEFPDDCCAP_BP6_USD%2BBEFPDDCRPP_BP6_USD%2BBEFPDOSA_BP6_USD%2BBEFPDOFCAI_BP6_USD%2BBEFPDOFRAI_BP6_USD%2BBEFPDCBSAP_BP6_USD%2BBEFPDORA_BP6_USD%2BBEFPDONFSAP_BP6_USD%2BBEFPDONFNS_BP6_USD%2BBEFPDORPI_BP6_USD%2BBEFPDOCA_BP6_USD%2BBEFPDOFSAP_BP6_USD%2BBEFPDOFRPI_BP6_USD%2BBEFPDDCCAI_BP6_USD%2BBEFPDOFNS_BP6_USD%2BBEFPDDCCA_BP6_USD%2BBEFPDONFRA_BP6_USD%2BBEFPDO_BP6_USD%2BBEFPDONFCA_BP6_USD%2BBEFPDOSAP_BP6_USD%2BBEFPDCBAAI_BP6_USD%2BBEFPDOPB_BP6_USD%2BBEFPDGAAPA_BP6_USD%2BBEFPDCBPB_BP6_USD%2BBEFPDGAAP_BP6_USD%2BBEFPDCBRPI_BP6_USD%2BBEFPDGAA_BP6_USD%2BBEFPDOCAP_BP6_USD%2BBEFPDOFAAI_BP6_USD%2BBEFPDONFCAI_BP6_USD%2BBEFPDGSA_BP6_USD%2BBEFP_BP6_USD) or pasting it into a browser (other than Google Chrome).

**Comment by giannilmbd** [comment]
Dear @vpinna80,
Thanks for your prompt reply!
I see. Indeed by being more selective it works (by omitting the set of countries, i.e. typing ".." in place of the countries, the chances to get the series are higher).
Best

**Comment by vpinna80** [comment]
@giannilmbd you're welcome :)
