### ISSUE TITLE
java error in MATLAB 2024a and MATLAB 2023b

### ISSUE THREAD

**Issue by 8eodosis** [amattioc/SDMX#254]
This java error appears in the last 2 versions:

**it.bancaditalia.oss.sdmx.helper.SDMXHelper lambda$updateSource$43

SEVERE: Exception. Class: java.lang.NoSuchMethodError .Message: org.codehaus.stax2.ri.SingletonIterator.create(Ljava/lang/Object;)Lorg/codehaus/stax2/ri/SingletonIterator;**

It was suggest that there is a workaround by mathworks: add this entry to the javaclasspath.txt in the preferences folder

C:\PATH\TO\stax2-api-4.2.2.jar

In MATLAB 22B the jar is located in

<MATLAB_DIR>/java/jarext/axis2/stax2-api.jar

I tried it but it didn't work.

**Comment by amattioc** [comment]
Hi @8eodosis ,

the problem is caused by a wrong java class being picked in MATLAB. We are investigating the root cause, for a definitive fix, but in the meantime I added a workaround (adaa19c5301f8d1fb059655e2238cd9cc2b214a6) in the code that should make it work.

You can apply it in directly in MATLAB typing:

`java.lang.System.setProperty("javax.xml.stream.XMLInputFactory", "com.sun.xml.internal.stream.XMLInputFactoryImpl");`

Please let me know if it works for you too.

**Comment by 8eodosis** [comment]
Thank you Attilio,
It works now
