### ISSUE TITLE
adding new Provider

### ISSUE THREAD

**Issue by Tungurahua** [amattioc/SDMX#43]
I am trying to add [FAO sdmx](http://data.fao.org/sdmx) as a new provider using `addProvider()`. However I am unsure what an "endpoint" is in this context. My first attempt has been:
```
# no Error received
addProvider("FAO","http://data.fao.org/sdmx")

# lists FAO as new source
getProviders()

# throws error
getFlows("FAO")
```
I suppose the url "http://data.fao.org/sdmx" is wrong. I tried to view the other Sources, but I understand that they are somewhere in the java code (?). Is there some resource that explains in more detail what I have to look out for when entering a new "endpoint"? Any hints would be appreciated.

**Comment by amattioc** [comment]
Hi, the **addProvider** function works only for 2.1 providers, because 2.0 ones are not sufficiently standardized (in 2.0 the WS API were not normative).

Usually it is enough to write down a *custom* provider in these cases (e.g. https://github.com/amattioc/SDMX/blob/master/JAVA/src/it/bancaditalia/oss/sdmx/client/custom/ABS.java), but unfortunatley in the FAO case the implementation is such that it is impossible to understand the DSD for a given dataset (or at least I did not find a way). 

I'll think a bit more about this situation...

**Comment by Tungurahua** [comment]
Hi, thanks for the answer. I already suspected something like this from reading the __addProvider__ help-files. However, the information given on the FAO website is rather vague

> The services interface are conform the specs for __SDMX 2.1__, except for the data and 
> datastructure artefacts. The data and datastructure artefacts are only available in __SDMX 2.0__.

Is there some way for me to check which endpoints would conform to __addProvider__? I suppose it is somewhere stated int he [DSD](http://data.fao.org/sdmx/registry/datastructure/FAO/FAOSTAT/1.0), but I don't know what I would be looking for.

I suppose that this information can be found somewhere in the SDMX-Specs, but frankly these documents are somewhat challenging to the un-initiated. Thus I would be very happy if you could provide me guidance here although the question is not exactly related to the RJSDMX code. 

Do you know of any Web-Forum (active and open to public) that addresses such questions (SDMX-specs etc.)?  If so, please let me know.

**Comment by amattioc** [comment]
Hi, the compliance with a particular version of the spacs should be stated by the provider, otherwise it is not easy to check it. Some time ago there was a discussion about the need of a 'technology compatibility toolkit', that could prove useful in these situations, but I don't know if this is going on.

Anyway, this is a set of precious resources that you can use as a reference:

* The [sdmx-rest](https://github.com/sdmx-twg/sdmx-rest) project on github, maintained by the SDMX TWG, and in particular the [tutorial](https://github.com/sdmx-twg/sdmx-rest/wiki) and the [cheat sheet](v2_1/ws/rest/docs/rest_cheat_sheet.pdf?raw=true). 
* The **sdmx user forum**: www.sdmxusers.org/
* The **SDMX group on Linkedin**
 
Best, Attilio

**Comment by Tungurahua** [comment]
Thanks a lot!

Best, Albrecht

**Comment by amattioc** [comment]
Closing as informational...
