### ISSUE TITLE
sdmxHelp() not starting under windows

### ISSUE THREAD

**Issue by Tungurahua** [amattioc/SDMX#49]
`sdmxHelp()` no longer starts under window. 

    > sdmxHelp()
    Warning message:
    running command 'java -classpath C:/Program Files/R/R-3.1.2/library/RJSDMX/java/SDMX.jar    
    it.bancaditalia.oss.sdmx.helper.SDMXHelper' had status 127 

I could open last weeks versions without problem

Also, how can I start `sdmxHelp2()` under Windows. Setting of a system command does not work here as `java` is not recognized as a command in the shell.

Any hints would be appreciated.

Best regards
Albrecht

**Comment by amattioc** [comment]
Hi, the problem is the same for the two helpers. You'll have to set the fully qualified path to JAVA as in your system a default is not set.

So, search the java executable and modify the **system** parameter this way:

*system(paste0('**path/to/java/java** -classpath ', file.path(find.package('RJSDMX'), 'java', 'SDMX.jar'), ' it.bancaditalia.oss.sdmx.helper.SDMXHelper'), wait=F)*

Let me know...

**Comment by amattioc** [comment]
I slightly changed the way the helper is spawned. Now theere is a parameter that decides if the used JVM is internal or external. Default is internal. In Os X external JVM should be used...

**Comment by Tungurahua** [comment]
Starting `sdmxHelp()` works nicely again. Thanks a lot!  I will check OsX tonight and let you know. 

If it were possible to make `sdmxHelp2()` available in the same manner it would be very helpful. Maybe include it as an internal function (e.g. `RJSDMX:::sdmxHelp2()` to recognize the fact that it's still a development version.

**Comment by amattioc** [comment]
in 8e9cd4c7936e0f70867879ef70f7f6d8123c8bb7 I switched the default helper for R. SDMXHelper2 will become the only helper available.
