### ISSUE TITLE
make getSDMX() return error code for non-successful retrieval 

### ISSUE THREAD

**Issue by Tungurahua** [amattioc/SDMX#50]
Sometimes `getSDMX()` is not able to retrieve the requested data. For Eurostat this is usually the case in the following two scenarios:

There is no data available for the specified ID e.g. 
`getSDMX(provider = "EUROSTAT",id = "teilm310.A.NSA.JOBRATE.TOTAL.C.")`

The amount of data is beyond a specific size limit e.g. 
`getSDMX(provider = "EUROSTAT",id = "nrg_110a.A.KTOE.2410..")`

In both cases I get an error message that reads `The query: XXX did not match any time series on the provider.`

While this is ok for downloading a single dataset it is a problem when I want to download a list of dataflow-ids using `lapply()`. Once an error is encountered, the `lapply()` breaks. Would it be possible to return an error code in these cases which I could use in a condition to avoid breaking the `lapply()` code?

An example of this situation is illustrated in the following gist
https://gist.github.com/Tungurahua/a1aa7044a3a46c8b8eec
in which for a list of dataflows the some information is extracted.

In both cases the EUROSTAT server returns a html message containing an error message. It would be ideal if this message could be returned in the R console. But as usual I don't know if this behaviour can be generalized over different REST-providers.

Best
Albrecht

**Comment by amattioc** [comment]
Hi, it is not always easy to undestand if the query did not return data because of an error or a real empty query, especially with mixed SDMX versions. For this reason I decided to always return an exception, so that the user could be confident in a (I hope) coherent behaviour.

Anyway I understand your point. Can I suggest to use try-catch and return NULL in case of errors? This is a modified version of your extractor. Could it be a solution (or sort of)?

`extractor <- function(dataflow){`
`  namelist <- names(getDimensions("EUROSTAT",dataflow))`
`  codelist <- lapply(namelist,function(x){getCodes("EUROSTAT",flow = dataflow,dimension = x )})`
`  dims <- sapply(codelist,function(x){names(x[1])})`
`  dims <- dims[1:(length(dims)-1)]`
`  idstring <- paste0(c(dataflow,dims), collapse=".")`
`  idstring <- paste0(idstring,".")`
`  dfout = NULL`
`  tryCatch({`
`    df <- getSDMX(provider = "EUROSTAT",id = idstring)`
`    df.meta <- sdmxdf(df,meta = T)`
`    df.meta <- df.meta[,!names(df.meta) %in% c("ID","STATUS")]`
 `   minimum <- min(as.numeric(as.character(df.meta$TIME)))`
 `   maximum <- max(as.numeric(as.character(df.meta$TIME)))`
 `   countries <- paste0(levels(df.meta$GEO), collapse = ", ")`
 `   dfout <- data.frame(Code=dataflow, Min=minimum, Max=maximum, Countries=countries)`
 ` }, error = function(e) {`
 `   print(e$message)`
 `   return(NULL)`
 ` })`
`  return(dfout)`
`}`

Best, Attilio

**Comment by Tungurahua** [comment]
Thanks, that definitely helps a lot and produces the intended result.
