### ISSUE TITLE
Problems with WB flows

### ISSUE THREAD

**Issue by Tungurahua** [amattioc/SDMX#61]
This problem is related to the `REF_AREA` dimension of the WDI (World Development indicators) from the `WB` provider. Then I use the following query that I built with the `sdmxHelp()` tool, I get error messages:

    > result = getTimeSeries('WB', 'WDI/A.SP_POP_TOTL.'); 
    Apr 27, 2015 10:52:38 AM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
    INFO: Contacting web service with query: http://api.worldbank.org/v2/data/WDI/.SP_POP_TOTL 
    Apr 27, 2015 10:52:42 AM it.bancaditalia.oss.sdmx.parser.v20.GenericDataParser setSeriesSingleObs
    WARNING: Invalid observation: '' for ts WDI.A.SP_POP_TOTL.1A. Setting NaN.
    Apr 27, 2015 10:52:42 AM it.bancaditalia.oss.sdmx.parser.v20.GenericDataParser setSeriesSingleObs
    WARNING: Invalid observation: '' for ts WDI.A.SP_POP_TOTL.S3. Setting NaN.
    Apr 27, 2015 10:52:42 AM it.bancaditalia.oss.sdmx.parser.v20.GenericDataParser setSeriesSingleObs
    [...] continues for other observations

The first thing to note is that  the query has one dimension less than the query strings which cause the warnings.

The second thing is that the two letter codes in the warning messages are not in line with what I get from issuing 

    getCodes("WB","WDI","REF_AREA")

The latter echos three letter country codes. 

I don't know if this is related to `RJSDMX` or to Worldbanks Rest-service. Any ideas?

**Comment by amattioc** [comment]
Hi Albrecht,
the WB provider is kind of different from the others (that's why I decided to mark it as **BETA** in the main picture and in the description). 

The things you notice regarding the code values (two letters vs three letters) are true and they depend on the provider. Anyway I think this can be considered a minor issue, since they work in both forms, e.g.:

`result = getTimeSeries('WB', 'WDI.A.SP_POP_TOTL.US'); `
and
`result = getTimeSeries('WB', 'WDI.A.SP_POP_TOTL.USA');` 

Regarding the key structure (missing frequency) in the result and in the real URL, this is the result of an adaptation that I deliberately decided to apply in order to align (as mush as possible) this provider to the others: you can see it in the custom client: [WB](https://github.com/amattioc/SDMX/blob/master/JAVA/src/it/bancaditalia/oss/sdmx/client/custom/WB.java). For reasons that I do not know, the WDI dataflow/dsd declares three dimensions, but the provider expects a query that only contains two (AREA and SERIES), and this breaks the common paradigm that the connectors use to correlate structure and data. FOr this reason I decided to add an adapting layer in the custom client, that lets the user interact with this provider *as if* it behaved as the others.

Incidentally, notice that the warning you see is not related to this aspect, but just to a data slot (in the time series)

**Comment by amattioc** [comment]
closed by mistake...

**Comment by Tungurahua** [comment]
Hi Attilio, thanks for the clarification. So the label `BETA` refers to the implementation of the WB connector, not to the WB  SDMX service itself?

What bugs me still is that there is no exact mapping between three- and two-letter codes. If I query `getCodes("WB","WDI","REF_AREA")` I get a list that's 237 entries in length. At the same time setting of `result = getTimeSeries('WB', 'WDI/A.SP_POP_TOTL.');` returns a list that contains has `REF_AREA` as a factor with 248 levels. The difference seems to be accounted for by some strange two-letter codes like `"1A" "S3" "B8" "Z4" "4E" "XC" "Z7" "7E" "EU" "F1" "XE" "XD" "XR" "XS" "ZJ" [...]` of which I cannot make any sense. Do you know where I can find the documentation of the WB data dimensions to clarify the meaning of these two-letter codes? 

Personally I would prefer tho retrieve the three-letter codes with the data as I can infer their meaning from the data attributes. However this would mean an extra step when merging data from different providers on the respective `country` field. 

Best
Albrecht

**Comment by amattioc** [comment]
Hi Albrecht, unfortunately replacing the 2 letter codes that get back with a data query wth the 3 letter ones would prereq a mapping table that the client (i.e. the connector, does not know). The alignment between data and metadata (structures and codes) is up to the provider, and the connector relies on that. 
You may want to ask the WB support some more details about these aspects, I'm sure they'll be happy to receive feedback from users.

Regading the 'BETA' label, it actually is applicable to both the provider (at least it was true at the time I had some interactions with WB) and to the connector.

Best, Attilio

**Comment by amattioc** [comment]
Hi @Tungurahua, if you have further questions/news about this feel free to reopen...
