### ISSUE TITLE
Handle timeouts

### ISSUE THREAD

**Issue by charphi** [amattioc/SDMX#88]
From time to time, some connections are hanging indefinitely.
So, it would be interesting to set timeouts for each client or at least globally.
In java, timeouts are set by `URLConnection#setConnectTimeout(long)` and `URLConnection#setReadTimeout(long)`.

**Comment by amattioc** [comment]
Hi @charphi , that's interesting. 

I've been thinking about timeouts some time ago, but I did not go ahead because it is not possible to set a 'one fits all' value. It really depends on what you're using the connectors for. 
E.g. sdmx helper users could benefit from shoter timeouts, while massive data retrievers from the longest possible ones.
It could be interesting to add a new configuration parameter to allow the user to override the default timeout maybe.
Anyway, I never experienced an indefinite wait on any provider and it could be useful to know where it happens, so that I can do some testing.

Thanks a lot.

**Comment by charphi** [comment]
In my tests, if a connection doesn't respond after a few minutes (usually 2 or 3 min), it won't respond at all and you better try again. (I'm working behind a corporate proxy and it might influence this behavior)

**Comment by amattioc** [comment]
Hi @charphi , please have a look if it fits your expectations. You can check the configuration details at:

https://github.com/amattioc/SDMX/wiki/System-Configuration#timeouts

**Comment by charphi** [comment]
Your solution is ok but I need to modify these values at runtime without using a properties file.
I have created a PR so you can see what kind of solution I'm thinking about.
