### ISSUE TITLE
Can not query DSD with 3 dimensions

### ISSUE THREAD

**Issue by agent96** [amattioc/SDMX#94]
Using R plugin, connecting to local store, DSD has 3 dimensions.  Using sdmxHelp to browse dataflows.  The check query creates a seriesKeysOnly query.  The resulting query (for all data) contains the following

/data/FLOW_ID/..?detail=seriesKeysOnly

the .. is interpreted as 'back up one level' and the query fails.  The keyword 'all' should be used instead
/data/FLOW_ID/all?detail=seriesKeysOnly

**Comment by amattioc** [comment]
Hi @agent96, thanks for the info. I made a quick test and it seems that the issue is provider specific. In details:

ABS: **OK**           --> RES_DWEL_ST/..
ECB: **OK**            --> EON/..
EUROSTAT: **OK** --> aact_ali01/..
INSEE: **OK**         --> ACT-TRIM-ANC/..
ISTAT: **FAIL**        --> 18_114/..
OECD: **FAIL**       --> AFA_CALC_OUT3/..
UNDATA: **FAIL** --> DF_UNDATA_WDI/..

I did not find three dimensions dsds in the remaining providers. Do you have any further examples?

Best, Attilio

**Comment by agent96** [comment]
It was encountered when connecting a new provider (a local instance of the Fusion Registry) web service.  The data was World Bank WDI.  I have encountered this issue before with the SDMX specification, where in a URL .. is treated as back up one level, so for instance
https://www.google.co.uk/fish/../and/../chips/../search?q=test
Is the same as
https://www.google.co.uk/search?q=test

This was raised as a potential issue with the REST API, the work around was to use the all keyword.

I don't know why some fail and some pass - I have looked at the ABS and this query is written as:
RES_DWELL/+.+.+/ABS?format=compact_v2

So this is why the '..' problem is not encountered.  The ISTAT fails as the query:
data/IT1,18_114,1.0/..?detail=serieskeysonly

Is rewritten as 
data/?detail=serieskeysonly

I'm not sure how the Eurostat query passes:
http://ec.europa.eu/eurostat/SDMX/diss-web/rest/data/ESTAT,aact_ali01,1.0/..?detail=serieskeysonly

**Comment by amattioc** [comment]
Thanks for the clarification. It helps investigating the best way to handle this.

**Comment by amattioc** [comment]
Hi @agent96 please check if the fix is fine for you. 
I decided to make it very minimalistic, modifying the behaviour of the helper only: this is the only place where the user cannot set the query by hand. 
It seems that the Eurostat provider is the only one that cannot handle the 'all' token, but this is not a big issues since it correctly responds to the double dot.

Best, Attilio
